import pandas as pd
from config import OUTPUT_DIR

class ScenarioFilter:
    def __init__(self):
        pass

    def filter_and_split(self, master_df):
        """
        Takes the master dataframe containing both Threshold 2 and 3 scenarios (if evaluated together),
        or assumes master_df has columns for 'Eligible_Thresh2' and 'Eligible_Thresh3'.
        Alternatively, this filters the dataframe based on the 'Eligible' column for a specific run.
        """
        # Assuming master_df was generated by running the engine for both thresholds and creating two columns,
        # or we run this per threshold. Let's assume we run the engine for both to generate comprehensive output.
        
        # If 'Eligible' is present, we filter by it.
        # But a better approach is to have Interaction Count and filter dynamically.
        
        if 'Interaction Count' not in master_df.columns:
            raise ValueError("Interaction Count missing from Master Data")

        # Threshold 2
        df_t2 = master_df[master_df['Interaction Count'] >= 2].copy()
        df_t2['Threshold Applied'] = 2
        df_t2['Eligible'] = 'YES'
        
        # Threshold 3
        df_t3 = master_df[master_df['Interaction Count'] >= 3].copy()
        df_t3['Threshold Applied'] = 3
        df_t3['Eligible'] = 'YES'
        
        # Non-eligible (Threshold 2 is baseline for any diversion usually, or 3 depending on user)
        # Let's define non-eligible as strictly < 2 for general case, or we provide non-eligible per threshold.
        df_non_eligible_t2 = master_df[master_df['Interaction Count'] < 2].copy()
        df_non_eligible_t3 = master_df[master_df['Interaction Count'] < 3].copy()

        # Route Combination (e.g., Entry-Exit Pairs)
        master_df['Route Combination'] = master_df['Entry DFC'].fillna('NONE') + " - " + master_df['Exit DFC'].fillna('NONE')

        return {
            "master": master_df,
            "threshold_2_eligible": df_t2,
            "threshold_3_eligible": df_t3,
            "threshold_2_non_eligible": df_non_eligible_t2,
            "threshold_3_non_eligible": df_non_eligible_t3
        }

    def generate_route_combination_summary(self, df):
        """
        Groups by Route Combination to calculate total tonnage and rakes.
        """
        if df.empty:
             return pd.DataFrame()
             
        df['Route Combination'] = df['Entry DFC'].fillna('NONE') + " - " + df['Exit DFC'].fillna('NONE')
        
        summary = df.groupby('Route Combination').agg(
            total_tonnage=('Annual Tonnage', 'sum'),
            total_rakes=('No. of Rakes / Wagon Units', 'sum'),
            od_count=('From Station Code', 'count')
        ).reset_index()
        
        # Filter out NONE - NONE
        summary = summary[summary['Route Combination'] != 'NONE - NONE']
        return summary
